export const projects = [
  {
    slug: 'cross-reality-dev',
    tag: 'XR / Game Dev',
    index: '01',
    title: 'Cross Reality Development',
    short: 'Unity URP — third-person movement, two connected scenes, scene transitions.',
    description:
      'Engine-based Cross Reality Development assignment built in Unity with the Universal Render Pipeline. Features two connected scenes, third-person player controller, scene transitions, and environment design using URP shaders and lighting.',
    lang: 'C#',
    year: '2026',
    color: '#ff4500',
    textColor: '#fff',
    githubUrl: 'https://github.com/Code-Abbey/cc241033',
    liveUrl: null,
  },
  {
    slug: 'harmonica-tab-app',
    tag: 'Mobile App',
    index: '02',
    title: 'Harmonica Tab App',
    short: 'Android app for browsing & practising chromatic harmonica tablature.',
    description:
      'Android application for browsing, editing, and practising chromatic harmonica tablature. Built with Jetpack Compose for a modern declarative UI and Room database for offline-first persistent storage. Features search, editing, and a dedicated practice mode.',
    lang: 'Kotlin',
    year: '2026',
    color: '#7c3aed',
    textColor: '#fff',
    githubUrl: 'https://github.com/Code-Abbey/ccl3_ws2025',
    liveUrl: 'https://code-abbey.github.io/ccl3_ws2025/',
  },
  {
    slug: 'creative-code-lab',
    tag: 'Creative Coding',
    index: '03',
    title: 'Creative Code Lab',
    short: 'Generative art and browser-based animation with vanilla JavaScript.',
    description:
      'A collection of interactive visual experiments exploring generative art, procedural drawing, and real-time browser animation. Built with vanilla JavaScript using Canvas API and WebGL techniques — no frameworks, pure creative computation.',
    lang: 'JavaScript',
    year: '2024',
    color: '#0284c7',
    textColor: '#fff',
    githubUrl: 'https://github.com/Code-Abbey/CCL1',
    liveUrl: 'https://code-abbey.github.io/CCL1/',
  },
  {
    slug: 'dfs-maze-solver',
    tag: 'Algorithms',
    index: '04',
    title: 'DFS Maze Solver',
    short: 'Graph-based maze solving using Depth-First Search in C#.',
    description:
      'A graph-based maze solver implementing Depth-First Search in C#. Includes a custom data-structure library, visual maze representation, step-by-step solution walkthrough, and a detailed technical report covering the algorithm analysis and complexity.',
    lang: 'C#',
    year: '2026',
    color: '#18181b',
    textColor: '#f5f4ef',
    githubUrl: 'https://github.com/Code-Abbey/MazeSolver',
    liveUrl: null,
  },
  {
    slug: 'expense-note-app',
    tag: 'Mobile App',
    index: '05',
    title: 'Expense Note App',
    short: 'Android expense tracker with categories, filters, and persistent storage.',
    description:
      'Android expense tracker built with Kotlin and Jetpack Compose. Uses Room for offline-first database storage and DataStore for user preferences. Features category management, date-range filtering, spending summaries, and a clean material design UI.',
    lang: 'Kotlin',
    year: '2026',
    color: '#0f766e',
    textColor: '#fff',
    githubUrl: 'https://github.com/Code-Abbey/ExpenseNoteApp',
    liveUrl: null,
  },
  {
    slug: 'minesweeper',
    tag: 'Web Game',
    index: '06',
    title: 'Minesweeper',
    short: 'Classic Minesweeper in the browser — timer, difficulty levels, responsive.',
    description:
      'Classic Minesweeper recreated from scratch in the browser using HTML, CSS, and vanilla JavaScript. Implements all original game mechanics — flood fill, flag placing, mine counting — plus a timer, three difficulty levels, and a fully responsive layout.',
    lang: 'JavaScript',
    year: '2025',
    color: '#15803d',
    textColor: '#fff',
    githubUrl: 'https://github.com/Code-Abbey/Minesweeper',
    liveUrl: 'https://code-abbey.github.io/Minesweeper/',
  },
  {
    slug: 'html-css-frontend',
    tag: 'Web Dev',
    index: '07',
    title: 'HTML & CSS Frontend',
    short: 'Responsive layouts and component patterns — grid, flexbox, modern CSS.',
    description:
      'A curated collection of responsive frontend layouts and UI components built with pure HTML and CSS. Covers advanced grid systems, flexbox patterns, CSS custom properties, and modern layout techniques without any JavaScript framework.',
    lang: 'HTML / CSS',
    year: '2025',
    color: '#b45309',
    textColor: '#fff',
    githubUrl: 'https://github.com/Code-Abbey/html_css_project',
    liveUrl: 'https://code-abbey.github.io/html_css_project/',
  },
  {
    slug: 'house-price-prediction',
    tag: 'Machine Learning',
    index: '08',
    title: 'House Price Prediction',
    short: 'Linear regression trained on housing data — my first ML project.',
    description:
      'Linear regression model trained to predict house prices from structured housing dataset. Built with scikit-learn, pandas, and NumPy — covers the full ML workflow: exploratory data analysis, feature engineering, model training, evaluation, and visualisation in Jupyter Notebook.',
    lang: 'Python',
    year: '2021',
    color: '#6d28d9',
    textColor: '#fff',
    githubUrl: 'https://github.com/Code-Abbey/House-Price-Prediction',
    liveUrl: null,
  },
  {
    slug: 'youtube-downloader',
    tag: 'Python Tool',
    index: '09',
    title: 'YouTube Downloader',
    short: 'CLI tool for downloading YouTube audio and video in multiple formats.',
    description:
      'Command-line tool for downloading YouTube content in multiple formats and quality levels. Supports audio-only extraction, quality selection, batch downloading, and progress feedback — built with Python using yt-dlp.',
    lang: 'Python',
    year: '2024',
    color: '#be123c',
    textColor: '#fff',
    githubUrl: 'https://github.com/Code-Abbey/Youtube_Downloader',
    liveUrl: null,
  },
  {
    slug: 'doings',
    tag: 'Full Stack',
    index: '10',
    title: 'Doings!',
    short: 'Role-based team task management app with React, Node.js, Express, and MongoDB.',
    description:
      'A full-stack team task management app built for small teams. Features role-based dashboards (Admin vs. User), task creation with deadlines and checklists, real-time checklist progress, Excel report export, file attachments, and secure JWT authentication with HTTP-only cookies. Frontend in React/Vite, backend in Node.js/Express, data in MongoDB Atlas.',
    lang: 'JavaScript',
    year: '2026',
    color: '#0f4c81',
    textColor: '#fff',
    githubUrl: 'https://github.com/Code-Abbey/doings',
    liveUrl: 'https://code-abbey.github.io/doings/',
  },
]

export const skillGroups = [
  { label: 'Languages', items: ['JavaScript', 'TypeScript', 'Python', 'C#', 'Kotlin', 'HTML', 'CSS'] },
  { label: 'Web & UI', items: ['React', 'Vite', 'Framer Motion', 'Jetpack Compose'] },
  { label: 'Game / XR', items: ['Unity', 'Universal Render Pipeline'] },
  { label: 'Data & ML', items: ['scikit-learn', 'pandas', 'NumPy', 'Jupyter'] },
  { label: 'Tools', items: ['Git', 'GitHub', 'Room DB', 'DataStore', 'Figma'] },
]

export const featured = ['doings', 'cross-reality-dev', 'harmonica-tab-app', 'creative-code-lab']
